name: Core
version: 0.1
author: Stormfox2
main: de.stormfox2.core.Core
commands:
  export:
    description: Export
    usage: /export <language>
  import:
    description: Import
    usage: /import <language>